### ISSUE TITLE
How to do error handling?

### ISSUE THREAD

**Issue by benwaffle** [ValaTox/tox-vapi#4]
We currently have private enums that map to Tox's errors, and we throw appropriately in each function.

``` Vala
[CCode (cprefix = "")]
private enum TOX_ERR_NEW {
    // ...
}

public errordomain ConstructError {
    // ...
}
```

Should we just expose the Tox error types? Or should we use `throw` (which we currently do)?
Considerations: Does it affect performance? Do we want to provide a high level API or a straight mapping to C?

**Comment by benwaffle** [comment]
It looks like non-gobject VAPIs in general don't convert errors in C to Vala `throws`. We should probably just map C to Vala in the VAPI and later, if needed, wrap it with high-level constructs (signals, exceptions, etc...) in the client.

**Comment by SkyzohKey** [comment]
I think that you're right, it would be better to just map the C library in the `toxcore.vapi` then make a library (`ToxCore.vala`) that would provide a correct wrapper for that vapi. Because using the vapi without modifying it looks like bullshit, if you have to pass an error each time you want to call a method, this will be boring in long-term. So the vapi + lib looks like a good solution :)
